services:
  people-jetson-base:
    extends:
      file: docker-compose-base.yaml
      service: people-base
    build:
      context: ./docker/people
      dockerfile: Dockerfile.jetson

  people-jetson-track-base:
    extends:
      service: people-jetson-base
    volumes:
      - ./cabot-common/cabot_common:/home/developer/people_ws/src/cabot_common
      - ./cabot-common/cabot_msgs:/home/developer/people_ws/src/cabot_msgs
      - ./cabot_people:/home/developer/people_ws/src/cabot_people
      - ./track_people_py:/home/developer/people_ws/src/track_people_py
      - ./track_people_msgs:/home/developer/people_ws/src/track_people_msgs
      - ./track_people_cpp:/home/developer/people_ws/src/track_people_cpp
      - ./lidar_process:/home/developer/people_ws/src/lidar_process
    command:
      - "/launch.sh"
      - "-W"                                # wait roscore
      - "-K"                                # tracking
      - "-O"                                # obstacle

  people-jetson-all-base:
    extends:
      service: people-jetson-base
    volumes:
      - ./cabot-common/cabot_common:/home/developer/people_ws/src/cabot_common
      - ./cabot-common/cabot_msgs:/home/developer/people_ws/src/cabot_msgs
      - ./cabot_people:/home/developer/people_ws/src/cabot_people
      - ./track_people_py:/home/developer/people_ws/src/track_people_py
      - ./track_people_msgs:/home/developer/people_ws/src/track_people_msgs
      - ./track_people_cpp:/home/developer/people_ws/src/track_people_cpp
      - ./lidar_process:/home/developer/people_ws/src/lidar_process
    command:
      - "/launch.sh"
      # - "/launch-core.sh"                 # use core dump
      - "-W"                                # wait roscore
      # - "-p"                                # people topic is simulation groundtruth
      - "-D"                                # detection
      - "-K"                                # tracking
      - "-O"                                # obstacle

  people-jetson-detection-base:
    extends:
      service: people-jetson
    command:
      - "/launch.sh"
      # - "/launch-core.sh"   # use core dump
      - "-W"                                # wait roscore
      # - "-p"                                # people topic is simulation groundtruth
      - "-D"                                # detection
      - "-a"                                # no resetrs individually

  people-jetson-framos-camera-base:
    extends:
      service: people-jetson
    command:
      - "/launch.sh"
      # - "/launch-core.sh"   # use core dump
      - "-W"                                # wait roscore
      # - "-p"                                # people topic is simulation groundtruth
      - "-c 2"                              # use FRAMOS camera
      - "-a"                                # no resetrs individually

  people-jetson-framos-detection-base:
    extends:
      service: people-jetson
    command:
      - "/launch.sh"
      # - "/launch-core.sh"   # use core dump
      - "-W"                                # wait roscore
      # - "-p"                                # people topic is simulation groundtruth
      - "-D"                                # detection

  people-jetson:
    extends:
      service: people-jetson-all-base
    volumes:
      - ./docker/home:/home/developer

  people-jetson-detection:
    extends:
      service: people-jetson-detection-base
    volumes:
      - ./docker/home:/home/developer