services:
  rs1-framos-camera:
    extends:
      file: docker-compose-jetson.yaml
      service: people-framos-jetson
    environment:
      - CABOT_CAMERA_NAME=rs1
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_1}
    command:
      - "/launch.sh"
      - "-a"
      - "-t"
      - "0"
      - "-c 2"
    cpuset: "11" # assume other processes don't use this cpu by isolcpus kernel option

  rs1-framos-detection:
    extends:
      file: docker-compose-jetson.yaml
      service: people-framos-jetson
    environment:
      - CABOT_USE_REALSENSE=0
      - CABOT_CAMERA_NAME=rs1
    command:
      - "/launch.sh"
      - "-D"

  rs2-framos-camera:
    extends:
      file: docker-compose-jetson.yaml
      service: people-framos-jetson
    environment:
      - CABOT_CAMERA_NAME=rs2
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_2}
    command:
      - "/launch.sh"
      - "-a"
      - "-t"
      - "0"
      - "-c 2"
    cpuset: "11" # assume other processes don't use this cpu by isolcpus kernel option

  rs2-framos-detection:
    extends:
      file: docker-compose-jetson.yaml
      service: people-framos-jetson
    environment:
      - CABOT_USE_REALSENSE=0
      - CABOT_CAMERA_NAME=rs2
    command:
      - "/launch.sh"
      - "-D"

  rs3-framos-camera:
    extends:
      file: docker-compose-jetson.yaml
      service: people-framos-jetson
    environment:
      - CABOT_CAMERA_NAME=rs3
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_3}
    command:
      - "/launch.sh"
      - "-a"
      - "-t"
      - "0"
      - "-c 2"
    cpuset: "11" # assume other processes don't use this cpu by isolcpus kernel option

  rs3-framos-detection:
    extends:
      file: docker-compose-jetson.yaml
      service: people-framos-jetson
    environment:
      - CABOT_USE_REALSENSE=0
      - CABOT_CAMERA_NAME=rs3
    command:
      - "/launch.sh"
      - "-D"

  track-framos:
    extends:
      file: docker-compose-jetson.yaml
      service: people-framos-jetson
    environment:
      - CABOT_USE_REALSENSE=0
    command:
      - "/launch.sh"
      - "-K"
