FROM cmucal/cabot_people-jetson:prod-ros2


RUN mkdir -p src
COPY track_people_py src/track_people_py
COPY track_people_msgs src/track_people_msgs
COPY track_people_cpp src/track_people_cpp
COPY cabot_people src/cabot_people

RUN /ros_entrypoint.sh colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release

