services:
  people:
    extends:
      file: docker-compose-base.yaml
      service: people-all-dev-base
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_REALSENSE=1

  people-prod:
    extends:
      file: docker-compose-base.yaml
      service: people-all-prod-base
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_REALSENSE=1

  people-framos:
    extends:
      file: docker-compose-base.yaml
      service: people-framos-all-dev-base
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_REALSENSE=1

  people-framos-prod:
    extends:
      file: docker-compose-base.yaml
      service: people-framos-all-prod-base
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_REALSENSE=1