version: "2.3"

services:
  people:
    extends:
      file: docker-compose-base.yaml
      service: people
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_REALSENSE=1

  people-framos:
    extends:
      file: docker-compose-base.yaml
      service: people-framos
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_REALSENSE=1