services:
  # dev
  rs1-dev:
    extends:
      file: docker-compose-base.yaml
      service: people-all-dev
    environment:
      - CABOT_CAMERA_NAME=rs1
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_1}
    command:
      - "/launch.sh"
      - "-a"
      - "-t"
      - "0"
      - "-D"
    profiles:
      - dev

  rs1-test-dev:
    extends:
      service: rs1-dev
    environment:
      - CABOT_GAZEBO=1
      - CABOT_USE_REALSENSE=0
    command:
      - "/launch.sh"
      - "-D"

  rs2-dev:
    extends:
      file: docker-compose-base.yaml
      service: people-all-dev
    environment:
      - CABOT_CAMERA_NAME=rs2
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_2}
    command:
      - "/launch.sh"
      - "-a"
      - "-t"
      - "0"
      - "-D"
    profiles:
      - dev

  rs2-test-dev:
    extends:
      service: rs2-dev
    environment:
      - CABOT_GAZEBO=1
      - CABOT_USE_REALSENSE=0
    command:
      - "/launch.sh"
      - "-D"

  rs3-dev:
    extends:
      file: docker-compose-base.yaml
      service: people-all-dev
    environment:
      - CABOT_CAMERA_NAME=rs3
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_3}
    command:
      - "/launch.sh"
      - "-a"
      - "-t"
      - "0"
      - "-D"
    profiles:
      - dev

  rs3-test-dev:
    extends:
      service: rs3-dev
    environment:
      - CABOT_GAZEBO=1
      - CABOT_USE_REALSENSE=0
    command:
      - "/launch.sh"
      - "-D"

  track-dev:
    extends:
      file: docker-compose-base.yaml
      service: people-all-dev
    environment:
      - CABOT_USE_REALSENSE=0
    command:
      - "/launch.sh"
      - "-K"
    profiles:
      - dev

  track-test-dev:
    extends:
      file: docker-compose-base.yaml
      service: people-all-dev
    environment:
      - CABOT_GAZEBO=1
      - CABOT_USE_REALSENSE=0
    command:
      - "/launch.sh"
      - "-K"
      - "-O"
      - "-T"
    profiles:
      - dev

  record-test-dev:
    extends:
      file: docker-compose-base.yaml
      service: people-all-dev
    environment:
      - CABOT_GAZEBO=1
      - CABOT_USE_REALSENSE=0
    command:
      - "/launch.sh"
      - "record_test"
    profiles:
      - dev

  # prodimg
  rs1-prod:
    extends:
      file: docker-compose-base.yaml
      service: people-all-prod
    environment:
      - CABOT_CAMERA_NAME=rs1
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_1}
    command:
      - "/launch.sh"
      - "-a"
      - "-t"
      - "0"
      - "-D"
    profiles:
      - prod

  rs1-test-prod:
    extends:
      service: rs1-prod
    environment:
      - CABOT_GAZEBO=1
      - CABOT_USE_REALSENSE=0
    command:
      - "/launch.sh"
      - "-D"
    profiles:
      - prod

  rs2-prod:
    extends:
      file: docker-compose-base.yaml
      service: people-all-prod
    environment:
      - CABOT_CAMERA_NAME=rs2
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_2}
    command:
      - "/launch.sh"
      - "-a"
      - "-t"
      - "0"
      - "-D"
    profiles:
      - prod

  rs2-test-prod:
    extends:
      service: rs2-prod
    environment:
      - CABOT_GAZEBO=1
      - CABOT_USE_REALSENSE=0
    command:
      - "/launch.sh"
      - "-D"
    profiles:
      - prod

  rs3-prod:
    extends:
      file: docker-compose-base.yaml
      service: people-all-prod
    environment:
      - CABOT_CAMERA_NAME=rs3
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_3}
    command:
      - "/launch.sh"
      - "-a"
      - "-t"
      - "0"
      - "-D"
    profiles:
      - prod

  rs3-test-prod:
    extends:
      service: rs3-prod
    environment:
      - CABOT_GAZEBO=1
      - CABOT_USE_REALSENSE=0
    command:
      - "/launch.sh"
      - "-D"
    profiles:
      - prod

  track-prod:
    extends:
      file: docker-compose-base.yaml
      service: people-all-prod
    environment:
      - CABOT_USE_REALSENSE=0
    command:
      - "/launch.sh"
      - "-K"
    profiles:
      - prod

  track-test-prod:
    extends:
      file: docker-compose-base.yaml
      service: people-all-prod
    environment:
      - CABOT_GAZEBO=1
      - CABOT_USE_REALSENSE=0
    command:
      - "/launch.sh"
      - "-K"
      - "-O"
      - "-T"
    profiles:
      - prod

  record-test-prod:
    extends:
      file: docker-compose-base.yaml
      service: people-all-prod
    environment:
      - CABOT_GAZEBO=1
      - CABOT_USE_REALSENSE=0
    command:
      - "/launch.sh"
      - "record_test"
    profiles:
      - prod
