version: "2.3"

services:
  people-base:
    build:
      context: ./docker/people
    environment:
      - DISPLAY
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,video,display
      - NVIDIA_VISIBLE_DEVICES=all
      - ROS_IP=${ROS_IP:-127.0.0.1}
      - GAZEBO_IP=${ROS_IP:-127.0.0.1}
      - ROS_MASTER_URI=http://${MASTER_IP:-127.0.0.1}:11311
      - GAZEBO_MASTER_URI=http://${MASTER_IP:-127.0.0.1}:11345
      - OMP_NUM_THREADS=1
      - ROS_LOG_DIR
# CaBot
      - CABOT_GAZEBO=${CABOT_GAZEBO:-1}
      - CABOT_SITE
      - CABOT_SHOW_PEOPLE_RVIZ=${CABOT_SHOW_PEOPLE_RVIZ:-0}
      - CABOT_USE_REALSENSE=${CABOT_USE_REALSENSE:-0}
      - CABOT_REALSENSE_SERIAL
      - CABOT_CAMERA_NAME
      - CABOT_CAMERA_RGB_FPS
      - CABOT_CAMERA_DEPTH_FPS
      - CABOT_CAMERA_RESOLUTION
      - CABOT_DETECT_VERSION=${CABOT_DETECT_VERSION:-3}
      - CABOT_HEADLESS
      - RMW_IMPLEMENTATION
      - CYCLONEDDS_URI
      - CYCLONEDDS_NETWORK_INTERFACE_NAME
      - CYCLONEDDS_NETWORK_INTERFACE_AUTODETERMINE # set automatically by launch.sh
    volumes:
      - /dev:/dev
      - /sys/devices:/sys/devices
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ./docker/home:/home/developer
    privileged: true
    devices:
      - /dev/dri
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    network_mode: host
    stop_signal: SIGINT
    stop_grace_period: 30s

  people:
    extends:
      service: people-base
    volumes:
      - ./cabot-common/cabot_common:/home/developer/people_ws/src/cabot_common
      - ./cabot-common/cabot_msgs:/home/developer/people_ws/src/cabot_msgs
      - ./cabot_people:/home/developer/people_ws/src/cabot_people
      - ./track_people_py:/home/developer/people_ws/src/track_people_py
      - ./track_people_msgs:/home/developer/people_ws/src/track_people_msgs
      - ./track_people_cpp:/home/developer/people_ws/src/track_people_cpp
    command:
      - "/launch.sh"
      # - "/launch-core.sh"                 # use core dump
      - "-W"                                # wait roscore
      # - "-p"                                # people topic is simulation groundtruth
      - "-D"                                # detection
      - "-K"                                # tracking
      - "-q"                                # queue
      - "-O"                                # obstacle

  people-detection:
    extends:
      service: people
    command:
      - "/launch.sh"
      # - "/launch-core.sh"   # use core dump
      - "-W"                                # wait roscore
      # - "-p"                                # people topic is simulation groundtruth
      - "-D"                                # detection
      - "-a"                                # no resetrs individually

