name: Run Unittest

on:
  push:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run_unittest:
    runs-on: ubuntu-22.04
    steps:
    - name: Maximize build space
      run:  |
            sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
            sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
            sudo rm -rf /opt/ghc
            echo "Available storage:"
            df -h
            docker system prune -a --volumes -f # delete unnecessary preinstalled docker images

    - uses: actions/checkout@v4

    - name: Install vcs
      run: pip3 install vcstool

    - name: Prepare thirdparty repos
      run: ./setup-dependency.sh

    - name: Pull images
      shell: bash
      run:  |
             docker pull cmucal/cabot-people:latest

    - name: Run unittest
      shell: bash
      run:  |
             export HOST_UID=$(id -u)
             export HOST_GID=$(id -g)
             # ./unittest.sh  # the following can be replaced with this once the image is updated
             docker compose --profile build run people ./src/cabot_people/script/unittest.sh -b -a